"""Adding relation table between users and programs

Revision ID: 2a2175c759ff
Revises: 920316077de2
Create Date: 2024-11-08 14:27:30.033889

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2a2175c759ff'
down_revision = '920316077de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_programs',
                    sa.Column('pk', sa.Integer(), nullable=False),
                    sa.Column('user_pk', sa.Integer(), nullable=False),
                    sa.Column('program_pk', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['program_pk'], ['programs.pk'], ),
                    sa.ForeignKeyConstraint(['user_pk'], ['users.pk'], ),
                    sa.PrimaryKeyConstraint('pk', 'user_pk', 'program_pk')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_programs')
    # ### end Alembic commands ###
