"""empty message

Revision ID: 3eb23f29754f
Revises: e52cc336be39
Create Date: 2024-11-09 21:11:19.548184

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3eb23f29754f'
down_revision = 'e52cc336be39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video', sa.String(), nullable=True))
        batch_op.drop_column('video_example')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_example', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('video')

    # ### end Alembic commands ###
