"""Editin exercise table

Revision ID: 7f838590e6e4
Revises: 3a24218c3d1d
Create Date: 2024-11-09 20:14:15.594278

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7f838590e6e4'
down_revision = '3a24218c3d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_tutorial', sa.String(), nullable=True))
        batch_op.drop_column('video_tutorial')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_tutorial', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('photo_tutorial')

    # ### end Alembic commands ###
