"""Adding programs table

Revision ID: 920316077de2
Revises: e3cd92594b14
Create Date: 2024-11-08 03:12:54.530342

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '920316077de2'
down_revision = 'e3cd92594b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
                    sa.Column('pk', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('pk')
                    )
    op.create_table('programs_exercises',
                    sa.Column('pk', sa.Integer(), nullable=False),
                    sa.Column('program_pk', sa.Integer(), nullable=False),
                    sa.Column('exercise_pk', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['exercise_pk'], ['exercises.pk'], ),
                    sa.ForeignKeyConstraint(['program_pk'], ['programs.pk'], ),
                    sa.PrimaryKeyConstraint('pk')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('programs_exercises')
    op.drop_table('programs')
    # ### end Alembic commands ###
