"""Creating whole project, again 

Revision ID: e3cd92594b14
Revises: 
Create Date: 2024-11-08 02:57:32.611973

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e3cd92594b14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
                    sa.Column('pk', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('video_tutorial', sa.String(), nullable=True),
                    sa.Column('exercise_type', sa.Enum('heavy_compound', 'isolation_exercise', name='exercisetype'),
                              server_default='heavy_compound', nullable=False),
                    sa.Column('author', sa.String(length=201), nullable=False),
                    sa.PrimaryKeyConstraint('pk'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('users',
                    sa.Column('pk', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(length=100), nullable=False),
                    sa.Column('last_name', sa.String(length=100), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('password', sa.String(length=255), nullable=False),
                    sa.Column('role', sa.Enum('user', 'super_user', 'trainer', 'admin', name='roletype'),
                              server_default='user', nullable=False),
                    sa.PrimaryKeyConstraint('pk'),
                    sa.UniqueConstraint('email')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('exercises')
    # ### end Alembic commands ###
